# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from window_export import Ui_ExportWindow
from datetime import date
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import  QSize



class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ExportWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 580)
        MainWindow.setFixedSize(899,580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ico/relatorio.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_relatorio = QtWidgets.QFrame(self.centralwidget)
        self.frame_relatorio.setEnabled(True)
        self.frame_relatorio.setGeometry(QtCore.QRect(0, 0, 900, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_relatorio.sizePolicy().hasHeightForWidth())
        self.frame_relatorio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.frame_relatorio.setFont(font)
        self.frame_relatorio.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:5px\n"
"\n"
"\n"
"\n"
"")
        self.frame_relatorio.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_relatorio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_relatorio.setObjectName("frame_relatorio")
        self.btn_salvar = QtWidgets.QPushButton(self.frame_relatorio)
        self.btn_salvar.setGeometry(QtCore.QRect(760, 510, 90, 30))
        self.btn_salvar.setStyleSheet("QPushButton {\n"
"    background-color:\"#0081D5\";\n"
"    border-radius: 5px;\n"
"    color:\"white\";\n"
"    font: 75 11pt \"Roboto Medium\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:\"#0093F2\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:\"#0075C1\"\n"
"}")
        self.btn_salvar.setObjectName("btn_salvar")
        self.btn_exportar = QtWidgets.QPushButton(self.frame_relatorio)
        self.btn_exportar.setGeometry(QtCore.QRect(650, 510, 90, 30))
        self.btn_exportar.setStyleSheet("QPushButton {\n"
"    background-color:\"#3AB44E\";\n"
"    border-radius: 5px;\n"
"    color:\"white\";\n"
"    font: 75 11pt \"Roboto Medium\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:\"#62CC74\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:\"#34A045\"\n"
"}")
        self.btn_exportar.setObjectName("btn_exportar")
        self.input_nome = QtWidgets.QLineEdit(self.frame_relatorio)
        self.input_nome.setGeometry(QtCore.QRect(420, 100, 430, 38))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.input_nome.setFont(font)
        self.input_nome.setTabletTracking(False)
        self.input_nome.setAccessibleDescription("")
        self.input_nome.setStyleSheet("QLineEdit {\n"
"    background-color:\"#FAFAFA\";\n"
"    border-radius:8px;\n"
"    border:1px solid;\n"
"    border-color: rgb(239, 239, 239);\n"
"    color:\"#777\";\n"
"    font: 10.5pt \"Quicksand\";\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border:2px solid \"#E3E3E3\"\n"
"}\n"
"")
        self.input_nome.setText("")
        self.input_nome.setObjectName("input_nome")
        self.label_nome_2 = QtWidgets.QLabel(self.frame_relatorio)
        self.label_nome_2.setGeometry(QtCore.QRect(421, 80, 47, 13))
        self.label_nome_2.setStyleSheet("font: 57 10.5pt \"Roboto Medium\";\n"
"color:\"#333333\"")
        self.label_nome_2.setObjectName("label_nome_2")
        self.label_email = QtWidgets.QLabel(self.frame_relatorio)
        self.label_email.setGeometry(QtCore.QRect(421, 160, 47, 13))
        self.label_email.setStyleSheet("font: 57 10.5pt \"Roboto\";\n"
"color:\"#333333\"")
        self.label_email.setObjectName("label_email")
        self.input_email = QtWidgets.QLineEdit(self.frame_relatorio)
        self.input_email.setGeometry(QtCore.QRect(420, 180, 430, 38))
        self.input_email.setStyleSheet("QLineEdit {\n"
"    background-color:\"#FAFAFA\";\n"
"    border-radius:8px;\n"
"    border:1px solid;\n"
"    border-color: rgb(239, 239, 239);\n"
"    color:\"#777\";\n"
"    font: 10.5pt \"Quicksand\";\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border:2px solid \"#E3E3E3\"\n"
"}\n"
"")
        self.input_email.setObjectName("input_email")
        self.input_telefone = QtWidgets.QLineEdit(self.frame_relatorio)
        self.input_telefone.setGeometry(QtCore.QRect(500, 260, 351, 38))
        self.input_telefone.setStyleSheet("QLineEdit {\n"
"    background-color:\"#FAFAFA\";\n"
"    border-radius:8px;\n"
"    border:1px solid;\n"
"    border-color: rgb(239, 239, 239);\n"
"    color:\"#777\";\n"
"    font: 10.5pt \"Quicksand\";\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border:2px solid \"#E3E3E3\"\n"
"}\n"
"")
        self.input_telefone.setObjectName("input_telefone")
        self.label_telefone = QtWidgets.QLabel(self.frame_relatorio)
        self.label_telefone.setGeometry(QtCore.QRect(501, 240, 61, 16))
        self.label_telefone.setStyleSheet("font: 57 10.5pt \"Roboto\";\n"
"color:\"#333333\"")
        self.label_telefone.setObjectName("label_telefone")
        self.textbox_caso = QtWidgets.QTextEdit(self.frame_relatorio)
        self.textbox_caso.setGeometry(QtCore.QRect(420, 350, 430, 141))
        self.textbox_caso.setStyleSheet("QTextEdit {\n"
"    background-color:\"#FAFAFA\";\n"
"    border-radius:8px;\n"
"    border:1px solid;\n"
"    border-color: rgb(239, 239, 239);\n"
"    color:\"#777\";\n"
"    font: 10.5pt \"Quicksand\";\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border:2px solid \"#E3E3E3\"\n"
"}\n"
"")
        self.textbox_caso.setObjectName("textbox_caso")
        self.Titulo = QtWidgets.QLabel(self.frame_relatorio)
        self.Titulo.setGeometry(QtCore.QRect(420, 20, 430, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.Titulo.setFont(font)
        self.Titulo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Titulo.setStyleSheet("font: 57 22.9pt \"Roboto Black\";\n"
"color: \"#0081D5\";")
        self.Titulo.setObjectName("Titulo")
        self.input_ddd = QtWidgets.QLineEdit(self.frame_relatorio)
        self.input_ddd.setGeometry(QtCore.QRect(420, 260, 61, 38))
        self.input_ddd.setStyleSheet("QLineEdit {\n"
"    background-color:\"#FAFAFA\";\n"
"    border-radius:8px;\n"
"    border:1px solid;\n"
"    border-color: rgb(239, 239, 239);\n"
"    color:\"#777\";\n"
"    font: 10.5pt \"Quicksand\";\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border:2px solid \"#E3E3E3\"\n"
"}\n"
"")
        self.input_ddd.setObjectName("input_ddd")
        self.label_relatorio = QtWidgets.QLabel(self.frame_relatorio)
        self.label_relatorio.setGeometry(QtCore.QRect(421, 320, 61, 16))
        self.label_relatorio.setStyleSheet("font: 57 10.5pt \"Roboto Medium\";\n"
"color:\"#333333\"")
        self.label_relatorio.setObjectName("label_relatorio")
        self.label_ddd = QtWidgets.QLabel(self.frame_relatorio)
        self.label_ddd.setGeometry(QtCore.QRect(421, 240, 61, 16))
        self.label_ddd.setStyleSheet("font: 57 10.5pt \"Roboto\";\n"
"color:\"#333333\"")
        self.label_ddd.setObjectName("label_ddd")
        self.image = QtWidgets.QLabel(self.frame_relatorio)
        self.image.setGeometry(QtCore.QRect(0, 0, 391, 561))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("Images/image-woman.png"))
        self.image.setObjectName("image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 21))
        self.menubar.setStyleSheet("background-color:\"#f6f6f6\";\n"
"border:0;\n"
"font: 10pt \"Roboto\";\n"
"")
        self.menubar.setObjectName("menubar")
        self.menuRelat_rio = QtWidgets.QMenu(self.menubar)
        self.menuRelat_rio.setStyleSheet("border:1px solid red;")
        self.menuRelat_rio.setObjectName("menuRelat_rio")
        self.menuEnvios = QtWidgets.QMenu(self.menubar)
        self.menuEnvios.setObjectName("menuEnvios")
        self.menuEvios = QtWidgets.QMenu(self.menubar)
        self.menuEvios.setObjectName("menuEvios")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuRelat_rio.menuAction())
        self.menubar.addAction(self.menuEnvios.menuAction())
        self.menubar.addAction(self.menuEvios.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.input_nome, self.input_email)
        MainWindow.setTabOrder(self.input_email, self.input_ddd)
        MainWindow.setTabOrder(self.input_ddd, self.input_telefone)
        MainWindow.setTabOrder(self.input_telefone, self.textbox_caso)
        MainWindow.setTabOrder(self.textbox_caso, self.btn_exportar)
        MainWindow.setTabOrder(self.btn_exportar, self.btn_salvar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Relatório Empresarial"))
        self.btn_salvar.setText(_translate("MainWindow", "Salvar"))
        self.btn_exportar.setText(_translate("MainWindow", "Exportar"))
        self.label_nome_2.setText(_translate("MainWindow", "Nome:"))
        self.label_email.setText(_translate("MainWindow", "E-mail:"))
        self.label_telefone.setText(_translate("MainWindow", "Telefone:"))
        self.textbox_caso.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Quicksand\'; font-size:10.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Titulo.setText(_translate("MainWindow", "RELATÓRIO DE ATENDIMENTO"))
        self.label_relatorio.setText(_translate("MainWindow", "Relatório:"))
        self.label_ddd.setText(_translate("MainWindow", "DDD:"))
        self.menuRelat_rio.setTitle(_translate("MainWindow", "Relatório"))
        self.menuEnvios.setTitle(_translate("MainWindow", "Cadastros"))
        self.menuEvios.setTitle(_translate("MainWindow", "Envios"))



        # Gravando dados
        def gravar_dados():
            try:
                nome = self.input_nome.text()
                email = self.input_email.text()
                ddd = self.input_ddd.text()
                telefone = self.input_telefone.text()
                caso = self.textbox_caso.toPlainText()
                data_atual = date.today()

                banco = sqlite3.connect('relatorios.db')
                cursor = banco.cursor()
                cursor.execute("CREATE TABLE IF NOT EXISTS dados (nome text, email text, ddd integer, telefone integer, caso text,  data integer)")
                
                if nome == '':
                   p()
                   print('ass')

                else:
                        cursor.execute("INSERT INTO dados (nome, email, ddd, telefone, caso, data) VALUES (?,?,?,?,?,?)", (nome , email, ddd, telefone, caso, data_atual))
                        cursor.close()
                        banco.commit()
                        print('executo')

                self.input_nome.setText('')
                self.input_email.setText('')
                self.input_ddd.setText('')
                self.input_telefone.setText('')
                self.textbox_caso.setText('')

            except:
                print(nome, email, ddd, telefone, caso, data_atual)
                print('Não foi possível conectar ao banco')
              

        # Action buttons
        self.btn_exportar.clicked.connect(self.openWindow)
        self.btn_salvar.clicked.connect(gravar_dados)


def p():
        print("não foi")
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setWindowIcon(QtGui.QIcon('ico/relatorio.ico'))
        msgBox.setText("Você precisar preencher o nome")
        msgBox.setWindowTitle("Informação")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.setStyleSheet("QPushButton {\n"
"    background-color:\"#3AB44E\";\n"
"    border-radius: 5px;\n"
"    color:\"white\";\n"
"    font: 75 11pt \"Roboto Medium\";\n"
"    width: 50px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:\"#62CC74\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:\"#34A045\"\n"
"}"

"QLabel { color:rgb(63, 63, 63); color:\"#333\"; font: 75 11pt \"Roboto\"; }"
"QWidget { background:\"transparent\";}"
"QFrame { background:\"red\"; padding-top:10px }"


)
   
        msgBox.exec_()

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Principal = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(Principal)
        Principal.show()
        sys.exit(app.exec_())
