# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_export.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportWindow(object):
    def setupUi(self, ExportWindow):
        ExportWindow.setObjectName("ExportWindow")
        ExportWindow.resize(413, 446)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ico/pdf.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ExportWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ExportWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_export = QtWidgets.QFrame(self.centralwidget)
        self.frame_export.setGeometry(QtCore.QRect(-10, -10, 801, 541))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.frame_export.setFont(font)
        self.frame_export.setStyleSheet("background:\"white\";")
        self.frame_export.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_export.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_export.setObjectName("frame_export")
        self.titulo_export = QtWidgets.QLabel(self.frame_export)
        self.titulo_export.setGeometry(QtCore.QRect(50, 40, 328, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.titulo_export.setFont(font)
        self.titulo_export.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.titulo_export.setStyleSheet("font: 57 22.9pt \"Roboto Black\";\n"
"color: \"#0081D5\";\n"
"text-transform: uppercase;\n"
"background:transparent;")
        self.titulo_export.setObjectName("titulo_export")
        self.label_select_data = QtWidgets.QLabel(self.frame_export)
        self.label_select_data.setGeometry(QtCore.QRect(50, 90, 121, 21))
        self.label_select_data.setStyleSheet("font: 57 10.5pt \"Roboto\";\n"
"color:\"#333333\"")
        self.label_select_data.setObjectName("label_select_data")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_export)
        self.calendarWidget.setGeometry(QtCore.QRect(50, 130, 341, 221))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setMouseTracking(False)
        self.calendarWidget.setTabletTracking(False)
        self.calendarWidget.setAcceptDrops(False)
        self.calendarWidget.setStyleSheet("color:\"#777\";")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.frame_export)
        self.label.setGeometry(QtCore.QRect(20, 20, 391, 361))
        self.label.setStyleSheet("border:3px solid \"#f5f5f5\";\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame_export)
        self.pushButton.setGeometry(QtCore.QRect(220, 400, 190, 35))
        self.pushButton.setStyleSheet("background-color:\"#3AB44E\";\n"
"border-radius: 5px;\n"
"color:\"white\";\n"
"font: 75 11pt \"Roboto Medium\";\n"
"text-transform: uppercase;")
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.titulo_export.raise_()
        self.label_select_data.raise_()
        self.calendarWidget.raise_()
        self.pushButton.raise_()
        ExportWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExportWindow)
        QtCore.QMetaObject.connectSlotsByName(ExportWindow)

    def retranslateUi(self, ExportWindow):
        _translate = QtCore.QCoreApplication.translate
        ExportWindow.setWindowTitle(_translate("ExportWindow", "Exportação de Relatório"))
        self.titulo_export.setText(_translate("ExportWindow", "Exportar Relatório"))
        self.label_select_data.setText(_translate("ExportWindow", "Selecione a Data:"))
        self.pushButton.setText(_translate("ExportWindow", "Exportar Relatório"))
